version: '3.7'
services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    ports:
      - 27017:27017
  web:
    build: .
    depends_on:
      - database
    ports:
      - 3000:3000
